'use server';

/**
 * @fileOverview Generates an image for a recipe using a text prompt.
 *
 * - generateRecipeImage - A function that handles the image generation.
 * - GenerateRecipeImageInput - The input type for the generateRecipeImage function.
 * - GenerateRecipeImageOutput - The return type for the generateRecipeImage function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateRecipeImageInputSchema = z.object({
  prompt: z.string().describe('A detailed text prompt describing the desired recipe image.'),
});
export type GenerateRecipeImageInput = z.infer<
  typeof GenerateRecipeImageInputSchema
>;

const GenerateRecipeImageOutputSchema = z.object({
  imageUrl: z.string().describe('The generated image as a data URI.'),
});
export type GenerateRecipeImageOutput = z.infer<
  typeof GenerateRecipeImageOutputSchema
>;

export async function generateRecipeImage(
  input: GenerateRecipeImageInput
): Promise<GenerateRecipeImageOutput> {
  return generateRecipeImageFlow(input);
}

const generateRecipeImageFlow = ai.defineFlow(
  {
    name: 'generateRecipeImageFlow',
    inputSchema: GenerateRecipeImageInputSchema,
    outputSchema: GenerateRecipeImageOutputSchema,
  },
  async ({prompt}) => {
    try {
      const {media} = await ai.generate({
        model: 'googleai/gemini-2.0-flash-preview-image-generation',
        prompt: prompt,
        config: {
          responseModalities: ['TEXT', 'IMAGE'],
        },
      });

      if (!media || !media.url) {
        throw new Error('No image was generated by the model.');
      }

      return {
        imageUrl: media.url,
      };
    } catch (error) {
      console.error(`Error generating recipe image for prompt "${prompt}":`, error);
      // Return a placeholder image on error to prevent the app from crashing.
      return {
        imageUrl: 'https://placehold.co/512x512.png',
      };
    }
  }
);
