-- ############
-- ### Tables
-- ############

-- Stores user-created recipes
CREATE TABLE public.my_recipies (
    id uuid NOT NULL DEFAULT uuid_generate_v4 (),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid NOT NULL DEFAULT auth.uid(),
    title text NOT NULL,
    details text,
    ingredients text[],
    time_to_cook text,
    featured_image_url text,
    result_image_urls text[],
    tags text[],
    category text,
    is_public boolean NOT NULL DEFAULT false,
    nutrition jsonb,
    CONSTRAINT my_recipies_pkey PRIMARY KEY (id),
    CONSTRAINT my_recipies_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON UPDATE CASCADE ON DELETE CASCADE
);
-- RLS Policy: Users can only manage their own recipes.
ALTER TABLE public.my_recipies ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view public recipes" ON public.my_recipies FOR SELECT USING (is_public = true);
CREATE POLICY "Users can manage their own recipes" ON public.my_recipies FOR ALL USING (auth.uid() = user_id);


-- Stores likes for recipes
CREATE TABLE public.likes (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid NOT NULL DEFAULT auth.uid(),
    recipe_id uuid NOT NULL,
    CONSTRAINT likes_pkey PRIMARY KEY (id),
    CONSTRAINT likes_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES public.my_recipies (id) ON DELETE CASCADE,
    CONSTRAINT likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE,
    CONSTRAINT likes_user_id_recipe_id_key UNIQUE (user_id, recipe_id)
);
-- RLS Policy: Users can only manage their own likes.
ALTER TABLE public.likes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view all likes" ON public.likes FOR SELECT USING (true);
CREATE POLICY "Users can manage their own likes" ON public.likes FOR ALL USING (auth.uid() = user_id);


-- Stores comments for recipes
CREATE TABLE public.comments (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid NOT NULL DEFAULT auth.uid(),
    recipe_id uuid NOT NULL,
    content text,
    user_full_name text,
    user_avatar_url text,
    CONSTRAINT comments_pkey PRIMARY KEY (id),
    CONSTRAINT comments_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES public.my_recipies (id) ON DELETE CASCADE,
    CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE
);
-- RLS Policy: Users can only manage their own comments.
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view all comments" ON public.comments FOR SELECT USING (true);
CREATE POLICY "Users can manage their own comments" ON public.comments FOR ALL USING (auth.uid() = user_id);


-- Stores user search history
CREATE TABLE public.history (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid NOT NULL DEFAULT auth.uid(),
    ingredients text[],
    recipes jsonb,
    image_url text,
    CONSTRAINT history_pkey PRIMARY KEY (id),
    CONSTRAINT history_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE
);
-- RLS Policy: Users can only manage their own history.
ALTER TABLE public.history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own history" ON public.history FOR ALL USING (auth.uid() = user_id);


-- ############
-- ### Functions
-- ############

-- Fetches all public recipes and includes interaction data for the requesting user.
-- Must be run with SECURITY DEFINER to access the auth.users table for owner details.
CREATE OR REPLACE FUNCTION get_public_recipes_with_interactions(request_user_id uuid)
RETURNS TABLE(
    id uuid,
    title text,
    featured_image_url text,
    category text,
    created_at timestamp with time zone,
    user_id uuid,
    is_public boolean,
    like_count bigint,
    comment_count bigint,
    has_liked boolean,
    owner_full_name text,
    owner_avatar_url text
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    r.id, r.title, r.featured_image_url, r.category, r.created_at, r.user_id, r.is_public,
    (SELECT COUNT(*) FROM likes WHERE recipe_id = r.id) AS like_count,
    (SELECT COUNT(*) FROM comments WHERE recipe_id = r.id) AS comment_count,
    (CASE WHEN request_user_id IS NOT NULL THEN
      EXISTS(SELECT 1 FROM likes li WHERE li.recipe_id = r.id AND li.user_id = request_user_id)
    ELSE
      false
    END) AS has_liked,
    u.raw_user_meta_data->>'full_name' AS owner_full_name,
    u.raw_user_meta_data->>'avatar_url' AS owner_avatar_url
  FROM my_recipies AS r
  JOIN auth.users AS u ON r.user_id = u.id
  WHERE r.is_public = true;
END;
$$;


-- Fetches recipes for a specific user and includes interaction data for the requesting user.
-- Must be run with SECURITY DEFINER to access the auth.users table for owner details.
CREATE OR REPLACE FUNCTION get_user_recipes_with_interactions(p_owner_id uuid, request_user_id uuid)
RETURNS TABLE(
    id uuid,
    title text,
    featured_image_url text,
    category text,
    created_at timestamp with time zone,
    user_id uuid,
    is_public boolean,
    like_count bigint,
    comment_count bigint,
    has_liked boolean,
    owner_full_name text,
    owner_avatar_url text
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    r.id, r.title, r.featured_image_url, r.category, r.created_at, r.user_id, r.is_public,
    (SELECT COUNT(*) FROM likes WHERE recipe_id = r.id) AS like_count,
    (SELECT COUNT(*) FROM comments WHERE recipe_id = r.id) AS comment_count,
    EXISTS(SELECT 1 FROM likes li WHERE li.recipe_id = r.id AND li.user_id = request_user_id) AS has_liked,
    u.raw_user_meta_data->>'full_name' AS owner_full_name,
    u.raw_user_meta_data->>'avatar_url' AS owner_avatar_url
  FROM my_recipies AS r
  JOIN auth.users AS u ON r.user_id = u.id
  WHERE r.user_id = p_owner_id;
END;
$$;


-- Finds public recipes that contain a given set of ingredients.
-- This function does not need SECURITY DEFINER as it does not access auth.users directly.
CREATE OR REPLACE FUNCTION find_recipes_by_ingredients(p_ingredients text[], p_request_user_id uuid)
RETURNS TABLE (
    id uuid,
    title text,
    featured_image_url text,
    category text,
    created_at text,
    user_id uuid,
    is_public boolean,
    like_count integer,
    comment_count integer,
    has_liked boolean,
    ingredients text[]
) 
AS $$
BEGIN
    RETURN QUERY
    SELECT
        r.id,
        r.title,
        r.featured_image_url,
        r.category,
        r.created_at::text,
        r.user_id,
        r.is_public,
        (SELECT count(*)::integer FROM likes l WHERE l.recipe_id = r.id) as like_count,
        (SELECT count(*)::integer FROM comments c WHERE c.recipe_id = r.id) as comment_count,
        EXISTS(SELECT 1 FROM likes li WHERE li.recipe_id = r.id AND li.user_id = p_request_user_id) AS has_liked,
        r.ingredients
    FROM
        my_recipies r
    WHERE
        r.is_public = true AND r.ingredients @> p_ingredients;
END;
$$ LANGUAGE plpgsql;
