-- This file documents the database schema for the ChefMate application.
-- This is for documentation purposes only and may not be the exact schema running in Supabase,
-- especially for policies which are managed in the Supabase UI.

-- User-created recipes table
CREATE TABLE public.my_recipies (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    title text NOT NULL,
    details text,
    ingredients text[],
    time_to_cook text,
    featured_image_url text,
    result_image_urls text[],
    tags text[],
    category text,
    is_public boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    nutrition jsonb
);
ALTER TABLE public.my_recipies ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow authenticated user to manage their own recipes" ON public.my_recipies FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Allow public read access to public recipes" ON public.my_recipies FOR SELECT USING (is_public = true);


-- Likes table for recipes
CREATE TABLE public.likes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id uuid NOT NULL REFERENCES public.my_recipies(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE (recipe_id, user_id)
);
ALTER TABLE public.likes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow authenticated users to manage their own likes" ON public.likes FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Allow all users to view likes" ON public.likes FOR SELECT USING (true);


-- Comments table for recipes
CREATE TABLE public.comments (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    recipe_id uuid NOT NULL REFERENCES public.my_recipies(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_full_name text,
    user_avatar_url text
);
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow authenticated users to manage their own comments" ON public.comments FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Allow all users to view comments" ON public.comments FOR SELECT USING (true);


-- User search history table
CREATE TABLE public.history (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    ingredients text[] NOT NULL,
    recipes jsonb,
    image_url text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE public.history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow authenticated users to manage their own history" ON public.history FOR ALL USING (auth.uid() = user_id);


-- Supabase Storage for recipe images
-- This is configured in the Supabase UI, but documented here for clarity.
-- A bucket named 'recipe-images' is used.
--
-- RLS policies for storage bucket 'recipe-images':
-- 1. Allow public read access to all images.
--    - Policy for: SELECT
--    - USING: true
--
-- 2. Allow authenticated users to upload, update, and delete their own images.
--    - Policy for: INSERT, UPDATE, DELETE
--    - USING: auth.uid() = (storage.foldername(name))[1]::uuid
--    - Note: This policy assumes images are stored in folders named after the user's ID,
--      e.g., 'public/recipe-images/<user_id>/image.jpg'. The front-end code handles this pathing.
